name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build application
        run: make

      - name: Deploy
        run: docker compose up -d --build

      - name: Restart frontend widget (background)
        run: | 
          pkill -f "run-frontend-widget" || true 
          nohup make run-frontend-widget > widget.log 2>&1 & disown